결손값 (NaN,Null) 값은 허용되지 않음 -> 따라서 null값은 고정된 다른 값으로 변환해야함

문자열 피쳐 - 1. 카테고리형 피처  - 피처 벡터화 기법으로 벡터화 or 불필요하다 판단된다면 드롭
                  ex) 주민번호, 단순 문자열 아이디
              2. 테스트형 피처 

## 데이터 인코딩

### 레이블 인코딩 (Lable encoding) 
카테고리 피처를 코드형 숫자 값으로 변환하는 것

LabelEncoder를 객체로 생성한 후 fit()과 transform()을 호출해 레이블 인코딩을 수행



In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder를 객체로 생성한 후 fit()과 transform()을 호출해 레이블 인코딩을 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


tv =0 , 냉장고 =1, 전자레인지=4, 컴퓨터=5, 선풍기=3, 믹서=2로 변환

In [5]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


-> classes_ 속성은 0번부터 순서대로 변환된 인코딩 값에 대한 원본값 보유

In [6]:
print('디코딩 클래스:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 클래스: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


-> encoder.inverse_transform()을 통해 인코딩된 값을 다시 디코딩

레이블 인코딩은 선형 회귀와 같은 ml알고리즘에 적용하지 않아야 함

트리 계열의 알고리즘은 숫자 특성을 반영하지 않기에 ㄱㅊ

### 원-핫 인코딩 (One Hot encoding)

피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고, 나머지 칼럼에는 0을 표시

1. 행->열 차원을 변환 
2. 해당 고유값에 매칭되는 피처만 1로 표시,  나머지 칼럼에는 0으로 표시

OneHotEncoder 클래스로 쉽게 변환

주의할 점 - 모든 문자열 값이 숫자형 값으로 변환되야함 ,입력값으로 2차원 데이터가 필요

In [7]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다. 
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 2차원 데이터로 변환합니다. 
labels = labels.reshape(-1,1)

# 원-핫 인코딩을 적용합니다. 
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


get_dummies() -> 원-핫 인코딩을 더 쉽게 지원하는 API

문자열 카테고리 값을 숫자 형으로 변환할 필요 없이 바로 변환 가능

In [8]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

### 피처 스케일링과 정규화
피처 스케일링 - 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업 ex)표준화, 정규화

#### StandardScaler - 표준화를 쉽게 지원하기 위한 클래스
개별 피처를 평균=0, 분산=1 로 변환

In [9]:
from sklearn.datasets import load_iris
import pandas as pd
# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환합니다. 
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [10]:
from sklearn.preprocessing import StandardScaler

# StandardScaler객체 생성
scaler = StandardScaler()
# StandardScaler 로 변환 대상 피처 데이터 셋 변환. fit( ) 과 transform( ) 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform( )시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### MinMaxScaler - 데이터 값을 0과 1사이의 범위 값으로 변환 (음수 : -1~1)

In [14]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler객체 생성
scaler = MinMaxScaler()
# MinMaxScaler 로 데이터 셋 변환. fit() 과 transform() 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최소 값')
print(iris_df_scaled.min())
print('\nfeature들의 최대 값')
print(iris_df_scaled.max())


feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [19]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

#학습 데이터는 0부터 10까지, 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
#Scaler 클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1,1)로 차원 변경
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

print(train_array.reshape(-1), test_array.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10] [0 1 2 3 4 5]


In [24]:
#MinMaxScaler객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1값으로 변환
scaler = MinMaxScaler()

#fit()하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로
scaler.fit(train_array)

#1/10 scale로 train_array 데이터 변환함. 원본 10->!로 변환됨.
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:', train_array.reshape(-1))
print('Scale된 train_array 데이터:', train_scaled.reshape(-1))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [25]:
#MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최솟값이 0,최댓값이 5로 설정됨
scaler.fit(test_array)

#1/5 scale로 test_array 데이터 변환함. 원본 5->1로 변환.
test_scaled = scaler.transform(test_array)

#test_array의 scale 변환 출력.
print('원본 train_array 데이터:', test_array.reshape(-1))
print('Scale된 train_array 데이터:', test_scaled.reshape(-1))

원본 train_array 데이터: [0 1 2 3 4 5]
Scale된 train_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


테스트 데이터는 최솟값 0, 최댓값 5이므로 1/5로 스케일링 1->0.2, 5->1 로 변환

머신러닝 모델은 학습 데이터를 기반으로 학습 - 반드시 테스트 데이터는 학습 데이터의 스케일링 기준에 따라야 함

테스트 데이터의 1값은 학습 데이터와 동일하게 0.1값으로 변환돼야 함

-> 따라서, 테스트 데이터는 학습데이터로 이미 fit()이 적용된 scaler 객체를 이용해 transform()으로 변환

In [26]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:', train_array.reshape(-1))
print('Scale된 train_array 데이터:', train_scaled.reshape(-1))

#test_array에 scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform()만으로 변환해야 함.
test_scaled = scaler.transform(test_array)
print('원본 train_array 데이터:', test_array.reshape(-1))
print('Scale된 train_array 데이터:', test_scaled.reshape(-1))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 train_array 데이터: [0 1 2 3 4 5]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]


##### 스케일링 변환 시 유의할 점

1. 가능하다면 전체 데이터의 스케일링 변환을 적용후 학습 | 테스트 분리

2. 1이 여의치 않다면, 테스트 데이터 변환시에는 학습데이터로 이미 fit()된 scaler 객체를 이용해 transform()으로 변환